# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameGuru' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "Alamofire"
pod "SwiftyJSON"
pod "AFNetworking"
pod "Firebase/Core"
pod "Firebase/Database"
pod "Firebase/Auth"
pod "Firebase/Storage"
pod "SVProgressHUD", :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'


  # Pods for gameGuru

  target 'gameGuruTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gameGuruUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
